# ______________Méthodes de classification  ________________

Analyse des données

In [1]:
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
import seaborn as sns
import matplotlib.pyplot as plt


In [2]:
data = pd.read_csv('./housing.csv')

In [3]:
data.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [4]:
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [5]:
data[data.isnull().any(axis=1)]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
290      -122.16     37.77                47.0       1256.0             NaN   
341      -122.17     37.75                38.0        992.0             NaN   
538      -122.28     37.78                29.0       5154.0             NaN   
563      -122.24     37.75                45.0        891.0             NaN   
696      -122.10     37.69                41.0        746.0             NaN   
...          ...       ...                 ...          ...             ...   
20267    -119.19     34.20                18.0       3620.0             NaN   
20268    -119.18     34.19                19.0       2393.0             NaN   
20372    -118.88     34.17                15.0       4260.0             NaN   
20460    -118.75     34.29                17.0       5512.0             NaN   
20484    -118.72     34.28                17.0       3051.0             NaN   

       population  households  median_income  median_house_value  \
290         570.0       218.0         4.3750            161900.0   
341         732.0       259.0         1.6196             85100.0   
538        3741.0      1273.0         2.5762            173400.0   
563         384.0       146.0         4.9489            247100.0   
696         387.0       161.0         3.9063            178400.0   
...           ...         ...            ...                 ...   
20267      3171.0       779.0         3.3409            220500.0   
20268      1938.0       762.0         1.6953            167400.0   
20372      1701.0       669.0         5.1033            410700.0   
20460      2734.0       814.0         6.6073            258100.0   
20484      1705.0       495.0         5.7376            218600.0   

      ocean_proximity  
290          NEAR BAY  
341          NEAR BAY  
538          NEAR BAY  
563          NEAR BAY  
696          NEAR BAY  
...               ...  
20267      NEAR OCEAN  
20268      NEAR OCEAN  
20372       <1H OCEAN  
20460       <1H OCEAN  
20484       <1H OCEAN  

[207 rows x 10 columns]

In [6]:
before_rows = data.shape[0]
print(before_rows)

20640


In [7]:
data = data.dropna()

In [8]:
after_rows = data.shape[0]
print(after_rows)

20433


In [9]:
before_rows - after_rows

207

# ________________Convertir en classification : ___________

In [10]:
clean_data = data.copy()
clean_data['ocean_proximity_INLAND_label'] = (clean_data['ocean_proximity'] == 'INLAND')*1
print(clean_data['ocean_proximity_INLAND_label'])

0        0
1        0
2        0
3        0
4        0
        ..
20635    1
20636    1
20637    1
20638    1
20639    1
Name: ocean_proximity_INLAND_label, Length: 20433, dtype: int32


In [11]:
y=clean_data[['ocean_proximity_INLAND_label']].copy()
#y

In [12]:
clean_data['ocean_proximity'].head()

0    NEAR BAY
1    NEAR BAY
2    NEAR BAY
3    NEAR BAY
4    NEAR BAY
Name: ocean_proximity, dtype: object

In [13]:
y.head()

ocean_proximity_INLAND_label
0                             0
1                             0
2                             0
3                             0
4                             0

In [14]:
housing_features = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value']

In [15]:
X = clean_data[housing_features].copy()

In [16]:
X.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [17]:
X.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value  
0       322.0       126.0         8.3252            452600.0  
1      2401.0      1138.0         8.3014            358500.0  
2       496.0       177.0         7.2574            352100.0  
3       558.0       219.0         5.6431            341300.0  
4       565.0       259.0         3.8462            342200.0

In [18]:
y.columns

Index(['ocean_proximity_INLAND_label'], dtype='object')

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=324)

In [20]:
y_train.describe()

ocean_proximity_INLAND_label
count                  13690.000000
mean                       0.314609
std                        0.464377
min                        0.000000
25%                        0.000000
50%                        0.000000
75%                        1.000000
max                        1.000000

# _______________Decision tree classifier ______________

In [21]:
ocean_proximity_INLAND_classifier = DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)
ocean_proximity_INLAND_classifier.fit(X_train, y_train)

DecisionTreeClassifier(max_leaf_nodes=10, random_state=0)

In [22]:
type(ocean_proximity_INLAND_classifier)

sklearn.tree._classes.DecisionTreeClassifier

In [23]:
predictions = ocean_proximity_INLAND_classifier.predict(X_test)

In [24]:
predictions[:10]

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 0], dtype=int32)

In [25]:
y_test['ocean_proximity_INLAND_label'][:10]

16882    0
20181    0
9433     0
7036     0
2961     1
1614     0
7065     0
9610     1
1991     1
17174    0
Name: ocean_proximity_INLAND_label, dtype: int32

In [26]:
accuracy_score(y_true = y_test, y_pred = predictions)

0.9136882693163281

# _______________________ KNN: _________________

In [27]:
ocean_proximity_INLAND_class = KNeighborsClassifier(n_neighbors=5)
ocean_proximity_INLAND_class.fit(X_train, y_train)

<ipython-input-27-73ae58a7e7da>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  ocean_proximity_INLAND_class.fit(X_train, y_train)


KNeighborsClassifier()

In [28]:
type(ocean_proximity_INLAND_class)

sklearn.neighbors._classification.KNeighborsClassifier

In [29]:
predictions = ocean_proximity_INLAND_class.predict(X_test)

In [30]:
predictions[:10]

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 0], dtype=int32)

In [31]:
y_test['ocean_proximity_INLAND_label'][:10]

16882    0
20181    0
9433     0
7036     0
2961     1
1614     0
7065     0
9610     1
1991     1
17174    0
Name: ocean_proximity_INLAND_label, dtype: int32

In [32]:
accuracy_score(y_true = y_test, y_pred = predictions)

0.8325671066290968

In [33]:
#_________________________________ Matrice de Confusion : ______________________

In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
confusion_matrix(y_true = y_test, y_pred = predictions)

array([[4114,  440],
       [ 689, 1500]], dtype=int64)

In [36]:
# ___________________________ Precision : ____________________

In [37]:
from sklearn.metrics import average_precision_score

In [38]:
average_precision = average_precision_score( y_test, y_score = predictions)

In [39]:
print('Average precision-recall score: {0:0.2f}'.format(average_precision))

Average precision-recall score: 0.63


# __________________________SVM: _______________________

In [40]:
clf = svm.SVC(kernel='linear')

In [ ]:
clf.fit(X_train, y_train)

C:\Users\pc\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [41]:
type(clf)

sklearn.svm._classes.SVC

In [ ]:
predictions =clf.predict(X_test)

In [ ]:
predictions[:10]

In [ ]:
y_test['ocean_proximity_INLAND_label'][:10]

In [ ]:
accuracy_score(y_true = y_test, y_pred = predictions)

In [43]:
from sklearn.metrics import confusion_matrix

In [44]:
confusion_matrix(y_true = y_test, y_pred = predictions)

array([[4114,  440],
       [ 689, 1500]], dtype=int64)

In [45]:
average_precision = average_precision_score( y_test, y_score = predictions)

In [46]:
print('Average precision-recall score: {0:0.2f}'.format(average_precision))

Average precision-recall score: 0.63


# __________________K-Folds Cross Validation _____________

In [47]:
from sklearn.model_selection import cross_val_score

In [ ]:
import numpy as np
cross = cross_val_score(clf, X, np.ravel(y), cv=5)

In [ ]:
type(cross)

In [ ]:
cross

# _____________________Naif Bayesien _________________________

In [64]:
from sklearn.naive_bayes import GaussianNB

In [65]:
nf = GaussianNB()

In [66]:
nf.fit(X_train, y_train)

C:\Users\pc\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


GaussianNB()

In [67]:
type(nf)

sklearn.naive_bayes.GaussianNB

In [68]:
predictions =kmeans.predict(X_test)

In [69]:
predictions[:10]

array([0, 1, 1, 1, 1, 0, 1, 1, 1, 0])

In [61]:
from sklearn.metrics import confusion_matrix

In [62]:
confusion_matrix(y_true = y_test, y_pred = predictions)

array([[1637, 2917],
       [ 106, 2083]], dtype=int64)

In [63]:
from sklearn.metrics import average_precision_score

In [49]:
average_precision = average_precision_score( y_test, y_score = predictions)

In [50]:
print('Average precision-recall score: {0:0.2f}'.format(average_precision))

Average precision-recall score: 0.63


# _______________________K-Means____________________ 

In [51]:
kmeans = KMeans(n_clusters=2, max_iter=600, algorithm = 'auto')

In [52]:
kmeans.fit(X_train)

KMeans(max_iter=600, n_clusters=2)

In [53]:
type(kmeans)

sklearn.cluster._kmeans.KMeans

In [54]:
predictions =kmeans.predict(X_test)

In [55]:
predictions[:10]

array([0, 1, 1, 1, 1, 0, 1, 1, 1, 0])

In [56]:
from sklearn.metrics import confusion_matrix

In [57]:
confusion_matrix(y_true = y_test, y_pred = predictions)

array([[1637, 2917],
       [ 106, 2083]], dtype=int64)

In [58]:
from sklearn.metrics import average_precision_score

In [59]:
average_precision = average_precision_score( y_test, y_score = predictions)

In [60]:
print('Average precision-recall score: {0:0.2f}'.format(average_precision))

Average precision-recall score: 0.41
